### ISSUE TITLE
Error 1006  Access denied

### ISSUE THREAD

**Issue by browningfai** [fuck91master/91porn_share#1]
Access denied
What happened?
The owner of this website (www.zhaiclub.com) has banned your IP address
 Performance & security by Cloudflare

**Comment by fuck91master** [comment]
Due to the high frequency of access, the ip address is blocked by cloudflare, if you need to unblock, please send me the ip address used

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
星期一, 八月 10, 2020 9:38 上午，browningfai <notifications@github.com> 来信：
